### ISSUE TITLE
Not compatible with lazy-loaded engines.

### ISSUE THREAD

**Issue by veelci** [linc-technologies/ember-spreadsheet-export#14]
Using :
- ember-cli 3.4.4
- ember-engines 0.8.5
- ember-spreadsheet-export 0.3.2

When building the project, which is a lazy-loaded engine, I get the following error:

  - broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, open '/home/ec2-user/workspace/the-lazy-engine/tmp/source_map_concat-input_base_path-JaVaBhFP.tmp/vendor/Blob.js'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at SourceMap.addFile (/home/ec2-user/workspace/the-lazy-engine/node_modules/fast-sourcemap-concat/lib/source-map.js:77:33)
    at /home/ec2-user/workspace/the-lazy-engine/node_modules/broccoli-concat/concat.js:204:18
    at Array.forEach (<anonymous>)
    at Concat.<anonymous> (/home/ec2-user/workspace/the-lazy-engine/node_modules/broccoli-concat/concat.js:202:26)
    at /home/ec2-user/workspace/the-lazy-engine/node_modules/fast-sourcemap-concat/lib/source-map.js:431:14
    at new Promise (<anonymous>)
    at SourceMap.end (/home/ec2-user/workspace/the-lazy-engine/node_modules/fast-sourcemap-concat/lib/source-map.js:418:12)
    at Concat._doLegacyBuild (/home/ec2-user/workspace/the-lazy-engine/node_modules/broccoli-concat/concat.js:187:24)
  - code: [undefined]
  - codeFrame: ENOENT: no such file or directory, open '/home/ec2-user/workspace/the-lazy-engine/tmp/source_map_concat-input_base_path-JaVaBhFP.tmp/vendor/Blob.js'
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `SourceMapConcat` plugin. 💥
ENOENT: no such file or directory, open '/home/ec2-user/workspace/the-lazy-engine/tmp/source_map_concat-input_base_path-JaVaBhFP.tmp/vendor/Blob.js'
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `SourceMapConcat` plugin. 💥
ENOENT: no such file or directory, open '/home/ec2-user/workspace/the-lazy-engine/tmp/source_map_concat-input_base_path-JaVaBhFP.tmp/vendor/Blob.js'
  - name: Error
  - nodeAnnotation: Concat: Vendor /assets/engine-vendor.js
  - nodeName: SourceMapConcat
  - originalErrorMessage: ENOENT: no such file or directory, open '/home/ec2-user/workspace/the-lazy-engine/tmp/source_map_concat-input_base_path-JaVaBhFP.tmp/vendor/Blob.js'
  - stack: Error: ENOENT: no such file or directory, open '/home/ec2-user/workspace/the-lazy-engine/tmp/source_map_concat-input_base_path-JaVaBhFP.tmp/vendor/Blob.js'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at SourceMap.addFile (/home/ec2-user/workspace/the-lazy-engine/node_modules/fast-sourcemap-concat/lib/source-map.js:77:33)
    at /home/ec2-user/workspace/the-lazy-engine/node_modules/broccoli-concat/concat.js:204:18
    at Array.forEach (<anonymous>)
    at Concat.<anonymous> (/home/ec2-user/workspace/the-lazy-engine/node_modules/broccoli-concat/concat.js:202:26)
    at /home/ec2-user/workspace/the-lazy-engine/node_modules/fast-sourcemap-concat/lib/source-map.js:431:14
    at new Promise (<anonymous>)
    at SourceMap.end (/home/ec2-user/workspace/the-lazy-engine/node_modules/fast-sourcemap-concat/lib/source-map.js:418:12)
    at Concat._doLegacyBuild (/home/ec2-user/workspace/the-lazy-engine/node_modules/broccoli-concat/concat.js:187:24)

**Comment by veelci** [comment]
@pauln, I opened a PR with some changes to get this working.  The main change was to import Blob.js from [blob-polyfill](https://github.com/bjornstar/blob-polyfill) instead of from vendor/Blob.js.

**Comment by veelci** [comment]
Since the PR was made, we are now using
```
ember-cli 3.16.2
ember-engines 0.8.20
```
and are still successfully running the branch.

**Comment by veelci** [comment]
@pauln Any updates on this PR?

**Comment by matthewhartstonge** [comment]
Hey @veelci, I'm currently going through upgrading this library.
I've had a look into the blob polyfill and decided to remove it based on the current state of the web (https://caniuse.com/?search=Blob) its fantastic how far we've come! 🎉

Hopefully this solves the lazy-loaded engine problem for you :)
